### ISSUE TITLE
Handle ONPs

### ISSUE THREAD

**Issue by kpjonsson** [zengzheng123/GetBaseCountsMultiSample#1]
Zeng,

Is it possible to let `GetBaseCountsMultiSample` deal with ONPs of arbitrary length? There are a few mutation callers that return this type of mutation.

**Comment by zengzheng123** [comment]
Do you have some examples(vcf and the corresponding bam files) that I can test?

**Comment by kpjonsson** [comment]
Yes, do you work on Luna?

**Comment by zengzheng123** [comment]
yes, you can send the path to my email, zeng@cbio.mskcc.org

**Comment by kpjonsson** [comment]
Will do, thanks!

**Comment by kpjonsson** [comment]
Fixed, not extensively tested but will close the issue.
