### ISSUE TITLE
Scientific notation (1.1e+06) issue with high coverage samples

### ISSUE THREAD

**Issue by NikdAK** [zengzheng123/GetBaseCountsMultiSample#11]
Hi,
thank you for the great tool.

Just to let you know: I found an issue regarding samples with an extreme read coverage. 
Here you can see that the output format of DP will be in scientific format (1.1e+06), which is causing all my downstream scripts to break due to unknown symbols (. e +).

I am using version 1.2.3 so I am not sure if you already fixed this, but this should be easy I guess.

Cheers

![image](https://user-images.githubusercontent.com/39265538/133061620-b45aadd4-fb7b-4d5a-8fa2-135229114273.png)

**Comment by zengzheng123** [comment]
Thank you for reporting the issue. I just merged a fix for it. Could you build the latest master branch and see if it solves the issue for you? Thank you.

**Comment by NikdAK** [comment]
Hi, thanks for the quick fix. 
There is a change, but now it needs an additional rounding to 0 decimal places on every column.
Cheers

![GetBaseCountsMultiSample_Bug2](https://user-images.githubusercontent.com/39265538/133631403-f2dd362a-5a80-47d8-a201-012784d93893.png)

**Comment by zengzheng123** [comment]
Just made some changes. Could you try again with the master branch?

**Comment by NikdAK** [comment]
Almost :) 

Now we just need setprecision to be defined I guess. This happens during make.

```
GetBaseCountsMultiSample.cpp: In function ‘void printCountsVcf(std::vector<VariantEntry*>&)’:
GetBaseCountsMultiSample.cpp:1127:18: error: ‘setprecision’ was not declared in this scope
     output_fs << setprecision(10);
                  ^~~~~~~~~~~~
GetBaseCountsMultiSample.cpp:1127:18: note: suggested alternative: ‘setresgid’
     output_fs << setprecision(10);
                  ^~~~~~~~~~~~
                  setresgid
GetBaseCountsMultiSample.cpp: In function ‘void printCountsFillout(std::vector<VariantEntry*>&)’:
GetBaseCountsMultiSample.cpp:1182:18: error: ‘setprecision’ was not declared in this scope
     output_fs << setprecision(10);
                  ^~~~~~~~~~~~
GetBaseCountsMultiSample.cpp:1182:18: note: suggested alternative: ‘setresgid’
     output_fs << setprecision(10);
                  ^~~~~~~~~~~~
                  setresgid
GetBaseCountsMultiSample.cpp: In function ‘void printCountsMaf(std::vector<VariantEntry*>&)’:
GetBaseCountsMultiSample.cpp:1227:18: error: ‘setprecision’ was not declared in this scope
     output_fs << setprecision(10);
                  ^~~~~~~~~~~~
GetBaseCountsMultiSample.cpp:1227:18: note: suggested alternative: ‘setresgid’
     output_fs << setprecision(10);
                  ^~~~~~~~~~~~
                  setresgid
makefile:2: recipe for target 'all' failed
make: *** [all] Error 1

```

**Comment by zengzheng123** [comment]
Sorry, I lost track of this issue. Just pushed another fix. Could you please try again and let me know if it works? Thank you.

**Comment by NikdAK** [comment]
Now it works as expected, thank you.
