### ISSUE TITLE
Remove newline character before parsing variant 

### ISSUE THREAD

**Issue by ckandoth** [zengzheng123/GetBaseCountsMultiSample#2]
In [this section of the code](https://github.com/zengzheng123/GetBaseCountsMultiSample/blob/v1.2.2/GetBaseCountsMultiSample.cpp#L786-L787), newline characters must be removed from `line` before it is split into columns, or else the last column will retain the newline character. You can [use this](https://github.com/mskcc/vcf2maf/blob/v1.6.16/tests/test.maf) as a test MAF, where GBCMS fails with the following error because the last column `n_alt_count` is not recognized by [this expression](https://github.com/zengzheng123/GetBaseCountsMultiSample/blob/v1.2.2/GetBaseCountsMultiSample.cpp#L797).

```
[ERROR] Incorrect input MAF file header. Make sure the following column headers exist in the MAF file:
[ERROR] Hugo_Symbol, Chromosome, Start_Position, End_Position, Reference_Allele, Tumor_Seq_Allele1, Tumor_Seq_Allele2, Tumor_Sample_Barcode, Matched_Norm_Sample_Barcode, t_ref_count, t_alt_count, n_ref_count, n_alt_count, Variant_Classification
```

**Comment by zengzheng123** [comment]
Hi, I tested it with the maf file you provided, but got no error. Could you provide more information? Thanks.

**Comment by ckandoth** [comment]
Thanks Zheng. You're right. That MAF works fine. I was using GBCMS with [our python wrapper](https://github.com/mskcc/cmo/blob/master/bin/cmo_fillout) which creates an intermediate MAF that is fed into GBCMS. And I just realized that it uses Windows newlines! So `\r\n` instead of `\n`. That MAF is attached below for reproducing the error.

[test_tmp.maf.txt](https://github.com/zengzheng123/GetBaseCountsMultiSample/files/2134787/test_tmp.maf.txt)

I will fix this in my wrapper, and you can close this issue, if you choose not to handle it in GBCMS too. Thanks!
